name: Simple Workflow

# Trigger this workflow on push to any branch
on:
  push:
    branches:
      - '*'

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run a simple command
      run: echo "Hello, DevOps World!"

    - name: Check Workflow Success
      run: echo "The workflow passed successfully!"
<<<<<<< HEAD
  launch-personal-site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run a Personal Site Load
      run: open "https://celestine.veracelservers.com"

    - name: Check Workflow Success
      run: echo "The workflow passed successfully!"
  launch-my-company-site:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Company Site load
      run: open "https://veracelservers.com"

    - name: Check Workflow Success
      run: echo "The workflow passed successfully!"
=======
>>>>>>> 4428c92e711a38f7fb5fccff8ebd6e5b0180d96d
